sudo: required
services:
  - docker

before_install:
  - docker build -t angelgoez/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run angelgoez/react-test npm test -- --coverage

after_success:
  - docker build -t angelgoez/multi-client ./client
  - docker build -t angelgoez/multi-nginx ./nginx
  - docker build -t angelgoez/multi-server ./server
  - docker build -t angelgoez/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_ID" --password-stdin
  - docker push angelgoez/multi-client 
  - docker push angelgoez/multi-nginx 
  - docker push angelgoez/multi-server 
  - docker push angelgoez/multi-worker 
